name: Create Issue
description: ❗ Ceate only if using Raspberry Pi & Raspbian OS ❗
title: "[Issue]: "
labels: [""]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Before making issue please meet Prerequisites
  
  - type: dropdown
    id: project
    attributes:
      label: Project
      multiple: true
      description: Which project/projects has issue ?
      options:
        - Aduard Home
        - Wireguard
        - Unbound
        - Cloudflare
        - Stubby 
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: Platform
      multiple: true
      description: Which platform/platforms is used?
      options:
        - Windows
        - Linux
        - Mac
        - Android
        - IOS
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser
      multiple: true
      description: Which browser/browsers has issue ?
      options:
        - Firefox
        - Chrome
        - Brave
        - Opera
        - Other 
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Issue Type (Optional)
      description: 
      options:
        - label: Not working
        - label: Not installing
        - label: Slow speeds
        - label: Other (explain in Issue description)
  - type: textarea
    id: what-happened
    attributes:
      label: Issue Description?
      description: 
      placeholder: 
      value:
    validations:
      required: true
