name: Create Issue
description: ❗ Ceate only if using Raspberry Pi & Raspbian OS ❗
title: "[Issue]: "
labels: [""]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Before making issue please meet Prerequisites
  
  - type: dropdown
    id: project
    attributes:
      label: Project
      multiple: true
      description: Which project/projects has issue ?
      options:
        - Aduard Home
        - Wireguard
        - Unbound
        - Cloudflare
        - Stubby 
    validations:
      required: true
  - type: dropdown
    id: platforms
    attributes:
      label: Platforms
      multiple: true
      description: Which platform/platforms is used?
      options:
        - Windows
        - Linux
        - Mac
        - Android
        - IOS
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Issue Type
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: Not working
        - label: Slow speeds
        - label: Not installing
        - label: Other
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
